FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY .docker/nginx.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist/ly-admin/browser /usr/share/nginx/html


CMD ["nginx", "-g", "daemon off;"]
